name: Working With Artifacts

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: thisartifact

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
        
