name: Full Build
on:
  workflow_dispatch:
    inputs:
      buildNumber:
        description: Insert build number.
        required: false
        default: ""

jobs:
  run-tests:
    - name: 'Browserstack Env Setup'
      uses: browserstack/github-actions/setup-env@master
      with:
        username: ${{ secrets.BSUSERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}

    - name: 'Browserstack Local Tunnel Setup'
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: start
        local-identifier: random

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: malformedbox/exclusiveSoup
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 'Building web application to be tested'
      run: mvn clean install

    - name: 'Running application under test'
      run: |
        mvn -B package --file pom.xml \
        -DsuiteType=full \
        -DsuiteXmlFile="fullSuite.xml" \
        -DdomainRoot=nightlyautomation \
        -Dcodebase=PROD \
        -DbuildNumber=123
        -Dtestplatform=BS \
        -DrunMode=PROD \
        -DbsUsername=${{ secrets.BSUSERNAME }} \
        -DbsAccessKey=${{ secrets.BSACCESSKEY }}

    - name: 'Browserstack local stop'
      uses: browserstack/github-actions/setup-local@master
      with:
        local-testing: stop