name: Test

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Get current date
        id: current-date
        run: |
          export TZ="America/New_York"
          echo "Current Date: $(date +'%Y-%m-%d')"
          echo "::set-output name=current_date::$(date +'%Y-%m-%d')"

      - name: Organize Allure History
        run: |
          current_date=$(echo "${{ steps.current-date.outputs.current_date }}")
          mkdir -p "$current_date"
          cp -r allure-history/* "$current_date"

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: "$current_date" # Publish to the current date folder

      - name: Post the link to the report
        if: always()
        uses: Sibz/github-status-action@v1
        with: 
          authToken: ${{secrets.GITHUB_TOKEN}}
          context: 'Test report'
          state: 'success'
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          target_url: https://malformedbox.github.io/exclusiveSoup/$current_date
