name: Test other folder
  
on:
  workflow_run:
    workflows: ["Workflow with inputs"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      test1:
        type: choice
        description: Test name 1
        options:
          - None
          - alwaysPass
          - alwaysFail
      test2:
        type: choice
        description: Test name 2
        options:
          - None
          - alwaysPass
          - alwaysFail

run-name: Test other folder - ${{ github.run_number}} - ${{ inputs.description }}
        
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
      
    steps:  
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Modify XML file
        run: |   
          map=("alwaysPass" "alwaysFail")

          selected1="${{ github.event.inputs.test1 }}"
          if [[ " ${map[*]} " == *" $selected1 "* ]]; then
            sed -i "s/exclude name=\"$selected1\"/include name=\"$selected1\"/g" src/resources/testng/full/fullSuite.xml
            echo "Running test1: $selected1"
          elif [[ "$selected1" == "None" ]]; then
            echo "Did not select a test to run."
          else
            echo "Invalid option selected: $selected1"
          fi

          selected2="${{ github.event.inputs.test2 }}"
          if [[ " ${map[*]} " == *" $selected2 "* ]]; then
            sed -i "s/exclude name=\"$selected2\"/include name=\"$selected2\"/g" src/resources/testng/full/fullSuite.xml
            echo "Running test2: $selected2"
          elif [[ "$selected2" == "None" ]]; then
            echo "Did not select a test to run."
          else
            echo "Invalid option selected: $selected2"
          fi
          
        shell: bash

      - name: Print test names that will be ran
        run: cat src/resources/testng/full/fullSuite.xml

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Generate Allure Report
        id: allureReport
        if: always()
        run: mvn allure:report

      # This is needed to grab Allure history
      - name: Get Allure history
        if: failure()
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      # This is needed to add history to the report
      - name: Build Report
        if: failure()
        uses: simple-elf/allure-report-action@master
        with:
          allure_results: target/allure-results
          allure_history: allure-history
          subfolder: workflow1
          keep_reports: 10 # Keeps only 10 previous history, oldest gets deleted
          
      - name: Deploy to Github Pages
        if: failure()
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
          
      - name: Post the link to the report
        if: failure()
        uses: Sibz/github-status-action@v1
        with: 
            authToken: ${{secrets.GITHUB_TOKEN}}
            context: 'Test report'
            state: 'success'
            sha: ${{ github.event.pull_request.head.sha || github.sha }}
            # Must be in https scheme and must match the subfolder's value in Build Report step
            target_url: https://malformedbox.github.io/exclusiveSoup/workflow1/${{ github.run_number}}
